apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: playground
spec:
  selector:
    app: sonarr
  ports:
  - protocol: TCP
    port: 8989        # internal cluster port
    targetPort: 8989
    nodePort: 32089   # external port on node
  type: NodePort
