apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: playground
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi
volumeMounts:
- name: music-data
  mountPath: /music
volumes:
- name: music-data
  persistentVolumeClaim:
    claimName: jellyfin-music-pvc
