apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: playground
  labels:
    app: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          env:
            - name: TZ
              value: "Europe/Lisbon"
          ports:
            - port: 80
              targetPort: 80
              nodePort: 30081
              protocol: TCP
              name: http
            - port: 53
              targetPort: 53
              nodePort: 30053
              protocol: TCP
              name: dns-tcp
            - port: 53
              targetPort: 53
              nodePort: 30053
              protocol: UDP
              name: dns-udp
          volumeMounts:
            - name: pihole-data
              mountPath: /etc/pihole
            - name: pihole-dnsmasq
              mountPath: /etc/dnsmasq.d
      volumes:
        - name: pihole-data
          persistentVolumeClaim:
            claimName: pihole-data
        - name: pihole-dnsmasq
          persistentVolumeClaim:
            claimName: pihole-dnsmasq
