apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: playground
spec:
  selector:
    app: prowlarr
  ports:
  - protocol: TCP
    port: 9696
    targetPort: 9696
    nodePort: 32096
  type: NodePort
