apiVersion: v1
kind: Service
metadata:
  name: gluetun
  namespace: playground
spec:
  selector:
    app: gluetun
  ports:
  - name: http
    port: 8888
    targetPort: 8888
  - name: dns
    port: 53
    targetPort: 53
  - name: vpn
    port: 51820
    targetPort: 51820
  type: ClusterIP
