apiVersion: apps/v1
kind: Deployment
metadata:
  name: gluetun
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
      - name: gluetun
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "mullvad"   # or protonvpn, pia, nordvpn, etc.
        - name: VPN_TYPE
          value: "wireguard" # or openvpn
        - name: VPN_ENDPOINT_IP
          value: "xx.xx.xx.xx"
        - name: VPN_ENDPOINT_PORT
          value: "51820"
        - name: VPN_INTERFACE
          value: "wg0"
        volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun
      volumes:
      - name: gluetun-config
        persistentVolumeClaim:
          claimName: gluetun-config
