apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-vpn
  namespace: playground
spec:
  selector:
    app: qbittorrent-vpn
  ports:
  - name: webui
    port: 8080
    targetPort: 8080
  type: NodePort
