apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-vpn
  namespace: playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-vpn
  template:
    metadata:
      labels:
        app: qbittorrent-vpn
    spec:
      containers:
      # 🔹 VPN container
      - name: gluetun
        image: qmcgaw/gluetun:latest
        securityContext:
          capabilities:
            add: ["NET_ADMIN"]
        env:
        - name: VPN_SERVICE_PROVIDER
          value: "mullvad"   # change to your VPN (nordvpn, pia, protonvpn...)
        - name: VPN_TYPE
          value: "openvpn" # or "openvpn"
        - name: VPN_INTERFACE
          value: "wg0"
        volumeMounts:
        - name: gluetun-config
          mountPath: /gluetun
      # 🔹 Torrent client container
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        env:
        - name: WEBUI_PORT
          value: "8080"
        ports:
        - containerPort: 8080  # qBittorrent Web UI
        - containerPort: 6881  # TCP for torrents
        - containerPort: 6881
          protocol: UDP        # UDP for torrents
        volumeMounts:
        - name: qbittorrent-config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: gluetun-config
        persistentVolumeClaim:
          claimName: gluetun-config
      - name: qbittorrent-config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: downloads
        persistentVolumeClaim:
          claimName: downloads-pvc
