apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: playground
spec:
  selector:
    app: qbittorrent
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32080
